package com.example.se114.local

object StringResources {
    val EN = mapOf(
        "tab_everyone" to "Everyone",
        "tab_foryou" to "For You",
        "tab_saved" to "Saved",
        "empty_saved_posts" to "No saved posts yet",
        "cancel" to "Cancel",
        "save" to "Save",
        "confirm" to "Confirm",
        "back" to "Back",
        "close" to "Close",
        "next" to "Next",
        "edit" to "Edit",
        "copy" to "Copy",
        "yes" to "Yes",
        "no" to "No",
        "profile_title" to "Profile",
        "account_settings" to "Account Settings",
        "account_data" to "Account Data",
        "help_support" to "Help & Support",
        "settings" to "Settings",
        "logout" to "Logout",
        "change_avatar" to "Change Avatar",
        "edit_profile" to "Edit Profile",
        "name" to "Name",
        "bio" to "Bio / Status",
        "name_empty_error" to "Name cannot be empty",
        "logout_confirm_title" to "Logout Confirmation",
        "logout_confirm_msg" to "Are you sure you want to logout?",
        "avatar_updated" to "Avatar updated!",
        "email" to "Email",
        "password" to "Password",
        "phone_number" to "Phone Number",
        "change_password" to "Change Password",
        "current_password" to "Current Password",
        "new_password" to "New Password",
        "confirm_password" to "Confirm Password",
        "passwords_not_match" to "Passwords do not match",
        "password_length_error" to "Password must be at least 6 characters",
        "verify_password" to "Verify Password",
        "verify_password_msg" to "Please enter your password to change phone number",
        "password_required" to "Password is required",
        "change_phone" to "Change Phone Number",
        "current" to "Current",
        "new_phone" to "New Phone Number",
        "phone_required" to "Phone number is required",
        "invalid_phone" to "Invalid phone number format",
        "address" to "Address",
        "gender" to "Gender",
        "current_job" to "Current Job",
        "edit_in_settings" to "Edit in Account Settings",
        "edit_address" to "Edit Address",
        "enter_address" to "Enter your address",
        "edit_job" to "Edit Current Job",
        "enter_job" to "Enter your current job",
        "field_empty_error" to "This field cannot be empty",
        "select_gender" to "Select Gender",
        "male" to "Male",
        "female" to "Female",
        "other" to "Other",
        "prefer_not_to_say" to "Prefer not to say",
        "need_help" to "Need Help?",
        "contact_support_msg" to "Contact our support team for assistance",
        "contact_info" to "Contact Information",
        "phone_copied" to "Phone number copied!",
        "email_copied" to "Email address copied!",
        "support_hours" to "Support Hours",
        "hours_detail" to "Monday - Friday: 8:00 AM - 8:00 PM\nSaturday - Sunday: 9:00 AM - 6:00 PM",
        "language" to "Language",
        "theme" to "Theme",
        "blocked_users" to "Blocked Users",
        "manage_blocked" to "Manage blocked accounts",
        "delete_account" to "Delete Account",
        "delete_account_msg" to "Permanently delete your account",
        "select_language" to "Select Language",
        "select_theme" to "Select Theme",
        "light_mode" to "Light Mode",
        "dark_mode" to "Dark Mode",
        "light_mode_desc" to "Bright and clean interface",
        "dark_mode_desc" to "Easy on the eyes, gentle colors",
        "apply" to "Apply",
        "no_blocked_users" to "No blocked users",
        "unblock" to "Unblock",
        "delete_account_title" to "Delete Account",
        "delete_warning_title" to "⚠️ This action cannot be undone!",
        "delete_warning_desc" to "• All your data will be permanently deleted\n• Your posts and comments will be removed\n• You cannot recover your account",
        "continue" to "Continue",
        "enter_password_continue" to "Enter your password to continue",
        "type_delete" to "Type 'DELETE' to confirm",
        "delete_forever" to "Delete Forever",
        "type_delete_exact" to "Please type DELETE exactly",
        "notifications" to "Notifications",
        "social" to "Social",
        "emergency" to "Emergency",
        "no_notifications" to "No notifications",
        "mark_all_read" to "Read all",
        "clear_all" to "Clear all",
        "social_empty_msg" to "Social interactions will appear here",
        "emergency_empty_msg" to "Emergency notifications will appear here",
        "just_now" to "Just now",
        "notif_liked_post" to "liked your post",
        "notif_commented" to "commented on your post",
        "notif_replied" to "replied to your comment",
        "notif_friend_request" to "sent you a friend request",
        "notif_sos_accepted" to "accepted to support your SOS post",
        "notif_emergency_approved" to "Your emergency request has been approved",
        "notif_emergency_rejected" to "Your emergency request requires more information",
        "time_just_now" to "Just now",
        "time_minutes_ago" to "m ago",
        "time_hours_ago" to "h ago",
        "time_days_ago" to "d ago",
        "time_weeks_ago" to "w ago",
        "time_months_ago" to "mo ago",
        "save_post" to "Save post",
        "unsave_post" to "Unsave post",
        "hide_post" to "Hide post",
        "report_post" to "Report post",
        "about_user" to "About",
        "report_title" to "Report post",
        "report_reason" to "Reason",
        "select_reason" to "Select a reason",
        "report_fraud" to "Fraud / Impersonation",
        "report_inappropriate" to "Inappropriate content",
        "report_trading" to "Trading",
        "report_offensive" to "Offensive",
        "report_misinformation" to "Misinformation",
        "report_other" to "Other",
        "report_description" to "Description (optional)",
        "report_description_hint" to "Provide more details...",
        "report_other_hint" to "Please specify the reason",
        "report_submit" to "Submit report",
        "report_cancel" to "Cancel",
        "report_select_reason_required" to "Please select a reason",
        "friend_accept" to "Accept",
        "friend_reject" to "Reject",
        "post_saved" to "Post saved!",
        "post_hidden" to "Post hidden",
        "report_success" to "Report submitted successfully",

        // Comments
        "comments" to "Comments",
        "write_comment" to "Write a comment...",
        "reply" to "Reply",
        "send" to "Send",
        "no_comments" to "No comments yet",
        "chat_title" to "Messages",
        "chat_search" to "Search...",
        "chat_all" to "All",
        "chat_unread" to "Unread",
        "chat_groups" to "Groups",
        "chat_active_now" to "Active now",
        "chat_type_message" to "Type a message...",
        "chat_auto_reply" to "Auto reply from bot ",
        "be_first_comment" to "Be the first to comment!",
        // --- EMERGENCY SCREEN ---
        "emergency_title" to "Emergency Center",
        "community_share" to "Community Share",
        "what_on_your_mind" to "What's on your mind?",
        "post_placeholder" to "Flood warning, traffic jam...",
        "post_button" to "Post",
        "post_success" to "Posted to Home!",
        "sos_title" to "SOS EMERGENCY",
        "sos_subtitle" to "Send signal to everyone",
        "sos_reason_label" to "What do you need help with?",
        "sos_reason_placeholder" to "Accident, breakdown, medical...",
        "sos_location_label" to "Where are you?",
        "sos_location_placeholder" to "Street name, district...",
        "sos_button" to "SEND SOS SIGNAL",
        "sos_success" to "SOS signal sent!",
        "delete" to "Delete",
        "phone_number" to "Phone Number",
        "phone_required" to "Phone number is required",
        "add_friend_title" to "Add New Friend",
        "add" to "Add",
        "enter_phone_placeholder" to "0901234567",
        "sos_error" to "Please enter all details!",

        // Other Profile
        "other_profile_title" to "Profile",
        "rating_score" to "Community Rating",
        "reviews" to "Reviews",
        "message" to "Message",
        "follow" to "Follow",
        "followed" to "Followed",
        "joined_date" to "Joined",
    )

    val VI = mapOf(
        "tab_everyone" to "Mọi người",
        "tab_foryou" to "Dành cho bạn",
        "tab_saved" to "Đã lưu",
        "empty_saved_posts" to "Chưa có bài viết đã lưu",
        "cancel" to "Hủy",
        "save" to "Lưu",
        "confirm" to "Xác nhận",
        "back" to "Quay lại",
        "close" to "Đóng",
        "next" to "Tiếp theo",
        "edit" to "Sửa",
        "copy" to "Sao chép",
        "yes" to "Có",
        "no" to "Không",
        "profile_title" to "Hồ sơ",
        "account_settings" to "Cài đặt tài khoản",
        "account_data" to "Dữ liệu cá nhân",
        "help_support" to "Trợ giúp & Hỗ trợ",
        "settings" to "Cài đặt",
        "logout" to "Đăng xuất",
        "logout_confirm_title" to "Xác nhận đăng xuất",
        "logout_confirm_msg" to "Bạn có chắc chắn muốn đăng xuất không?",
        "avatar_updated" to "Đã cập nhật ảnh đại diện!",
        "change_avatar" to "Đổi ảnh đại diện",
        "edit_profile" to "Chỉnh sửa hồ sơ",
        "name" to "Tên",
        "bio" to "Tiểu sử / Trạng thái",
        "name_empty_error" to "Tên không được để trống",
        "email" to "Email",
        "password" to "Mật khẩu",
        "phone_number" to "Số điện thoại",
        "change_password" to "Đổi mật khẩu",
        "current_password" to "Mật khẩu hiện tại",
        "new_password" to "Mật khẩu mới",
        "confirm_password" to "Xác nhận mật khẩu",
        "passwords_not_match" to "Mật khẩu không khớp",
        "password_length_error" to "Mật khẩu phải có ít nhất 6 ký tự",
        "verify_password" to "Xác thực mật khẩu",
        "verify_password_msg" to "Vui lòng nhập mật khẩu để đổi số điện thoại",
        "password_required" to "Vui lòng nhập mật khẩu",
        "change_phone" to "Đổi số điện thoại",
        "current" to "Hiện tại",
        "new_phone" to "Số điện thoại mới",
        "phone_required" to "Vui lòng nhập số điện thoại",
        "invalid_phone" to "Định dạng số điện thoại không hợp lệ",
        "address" to "Địa chỉ",
        "gender" to "Giới tính",
        "current_job" to "Công việc hiện tại",
        "edit_in_settings" to "Chỉnh sửa trong Cài đặt tài khoản",
        "edit_address" to "Sửa địa chỉ",
        "enter_address" to "Nhập địa chỉ của bạn",
        "edit_job" to "Sửa công việc hiện tại",
        "enter_job" to "Nhập công việc hiện tại",
        "field_empty_error" to "Trường này không được để trống",
        "select_gender" to "Chọn giới tính",
        "male" to "Nam",
        "female" to "Nữ",
        "other" to "Khác",
        "prefer_not_to_say" to "Không muốn tiết lộ",
        "need_help" to "Cần trợ giúp?",
        "contact_support_msg" to "Liên hệ đội ngũ hỗ trợ để được giúp đỡ",
        "contact_info" to "Thông tin liên hệ",
        "phone_copied" to "Đã sao chép số điện thoại!",
        "email_copied" to "Đã sao chép địa chỉ email!",
        "support_hours" to "Giờ làm việc",
        "hours_detail" to "Thứ 2 - Thứ 6: 8:00 Sáng - 8:00 Tối\nThứ 7 - Chủ Nhật: 9:00 Sáng - 6:00 Tối",
        "language" to "Ngôn ngữ",
        "theme" to "Giao diện",
        "blocked_users" to "Người dùng đã chặn",
        "manage_blocked" to "Quản lý danh sách chặn",
        "delete_account" to "Xóa tài khoản",
        "delete_account_msg" to "Xóa vĩnh viễn tài khoản của bạn",
        "select_language" to "Chọn ngôn ngữ",
        "select_theme" to "Chọn giao diện",
        "light_mode" to "Chế độ Sáng",
        "dark_mode" to "Chế độ Tối",
        "light_mode_desc" to "Giao diện sáng sủa và sạch sẽ",
        "dark_mode_desc" to "Dịu mắt, tông màu nhẹ nhàng",
        "apply" to "Áp dụng",
        "no_blocked_users" to "Không có người dùng bị chặn",
        "unblock" to "Bỏ chặn",
        "delete_account_title" to "Xóa Tài Khoản",
        "delete_warning_title" to "⚠️ Hành động này không thể hoàn tác!",
        "delete_warning_desc" to "• Tất cả dữ liệu của bạn sẽ bị xóa vĩnh viễn\n• Bài đăng và bình luận sẽ bị gỡ bỏ\n• Bạn không thể khôi phục tài khoản",
        "continue" to "Tiếp tục",
        "enter_password_continue" to "Nhập mật khẩu để tiếp tục",
        "type_delete" to "Gõ 'DELETE' để xác nhận",
        "delete_forever" to "Xóa Vĩnh Viễn",
        "type_delete_exact" to "Vui lòng gõ chính xác chữ DELETE",
        "notifications" to "Thông báo",
        "social" to "Xã hội",
        "emergency" to "Khẩn cấp",
        "no_notifications" to "Không có thông báo",
        "mark_all_read" to "Đọc tất cả",
        "clear_all" to "Xóa tất cả",
        "social_empty_msg" to "Các tương tác xã hội sẽ xuất hiện ở đây",
        "emergency_empty_msg" to "Các thông báo khẩn cấp sẽ xuất hiện ở đây",
        "just_now" to "Vừa xong",
        "notif_liked_post" to "đã thích bài viết của bạn",
        "notif_commented" to "đã bình luận",
        "notif_replied" to "đã trả lời bình luận của bạn",
        "notif_friend_request" to "đã gửi lời mời kết bạn",
        "notif_sos_accepted" to "đã chấp nhận hỗ trợ bài đăng SOS của bạn",
        "notif_emergency_approved" to "Yêu cầu khẩn cấp của bạn đã được duyệt",
        "notif_emergency_rejected" to "Yêu cầu khẩn cấp của bạn cần thêm thông tin",
        "time_just_now" to "Vừa xong",
        "time_minutes_ago" to "phút trước",
        "time_hours_ago" to "giờ trước",
        "time_days_ago" to "ngày trước",
        "time_weeks_ago" to "tuần trước",
        "time_months_ago" to "tháng trước",
        "save_post" to "Lưu bài viết",
        "unsave_post" to "Bỏ lưu bài viết",
        "hide_post" to "Ẩn bài viết",
        "report_post" to "Báo cáo bài viết",
        "about_user" to "Về",
        "report_title" to "Báo cáo bài viết",
        "report_reason" to "Lý do",
        "select_reason" to "Chọn lý do",
        "report_fraud" to "Lừa đảo / Giả danh",
        "report_inappropriate" to "Nội dung không phù hợp",
        "report_trading" to "Buôn bán",
        "report_offensive" to "Xúc phạm",
        "report_misinformation" to "Thông tin sai sự thật",
        "report_other" to "Khác",
        "report_description" to "Mô tả (tùy chọn)",
        "report_description_hint" to "Cung cấp thêm chi tiết...",
        "report_other_hint" to "Vui lòng nêu rõ lý do",
        "report_submit" to "Gửi báo cáo",
        "report_cancel" to "Hủy",
        "report_select_reason_required" to "Vui lòng chọn lý do",
        "friend_accept" to "Chấp nhận",
        "friend_reject" to "Từ chối",
        "post_saved" to "Đã lưu bài viết!",
        "post_hidden" to "Đã ẩn bài viết",
        "report_success" to "Gửi báo cáo thành công",

        // Comments
        "comments" to "Bình luận",
        "write_comment" to "Viết bình luận...",
        "reply" to "Trả lời",
        "send" to "Gửi",
        "no_comments" to "Chưa có bình luận",
        "chat_title" to "Tin nhắn",
        "chat_search" to "Tìm kiếm...",
        "chat_all" to "Tất cả",
        "chat_unread" to "Chưa đọc",
        "chat_groups" to "Nhóm",
        "chat_active_now" to "Đang hoạt động",
        "chat_type_message" to "Nhập tin nhắn...",
        "chat_auto_reply" to "Trả lời tự động từ bot ",
        "be_first_comment" to "Hãy là người đầu tiên bình luận!",
        // --- MÀN HÌNH KHẨN CẤP ---
        "emergency_title" to "Trung tâm Khẩn cấp",
        "community_share" to "Chia sẻ cộng đồng",
        "what_on_your_mind" to "Bạn đang nghĩ gì?",
        "post_placeholder" to "Cảnh báo ngập lụt, kẹt xe...",
        "post_button" to "Đăng bài",
        "post_success" to "Đã đăng lên Trang chủ!",
        "sos_title" to "SOS KHẨN CẤP",
        "sos_subtitle" to "Gửi tín hiệu đến tất cả mọi người",
        "sos_reason_label" to "Bạn đang cần giúp gì?",
        "sos_reason_placeholder" to "Tai nạn, hỏng xe, y tế...",
        "sos_location_label" to "Bạn đang ở đâu?",
        "sos_location_placeholder" to "Số nhà, tên đường, quận...",
        "sos_button" to "GỬI TÍN HIỆU CẦU CỨU",
        "sos_success" to "Đã gửi tín hiệu SOS!",
        "delete" to "Xóa",
        "phone_number" to "Số điện thoại",
        "phone_required" to "Vui lòng nhập số điện thoại",
        "add_friend_title" to "Thêm bạn mới",
        "add" to "Thêm",
        "enter_phone_placeholder" to "0901234567",
        "sos_error" to "Vui lòng nhập đầy đủ thông tin!",

        // Other Profile
        "other_profile_title" to "Thông tin cá nhân",
        "rating_score" to "Đánh giá cộng đồng",
        "reviews" to "Đánh giá",
        "message" to "Nhắn tin",
        "follow" to "Theo dõi",
        "followed" to "Đã theo dõi",
        "joined_date" to "Tham gia",
    )
}