package com.example.se114.local

object StringResources {
    val EN = mapOf(
        // Common
        "email_exists_error" to "This email is already registered.",
        "unknown_error" to "An unknown error occurred.",
        "app_name" to "LocaSOS",
        "cancel" to "Cancel",
        "save" to "Save",
        "confirm" to "Confirm",
        "back" to "Back",
        "close" to "Close",
        "next" to "Next",
        "edit" to "Edit",
        "copy" to "Copy",
        "yes" to "Yes",
        "no" to "No",
        "apply" to "Apply",
        "loading" to "Loading...",
        "error" to "Error",
        "success" to "Success",
        "delete" to "Delete",
        "search" to "Search",

        // Auth
        "login" to "Login",
        "register" to "Register",
        "forgot_password" to "Forgot Password",
        "email" to "Email",
        "password" to "Password",
        "phone_number" to "Phone Number",
        "full_name" to "Full Name",
        "login_success" to "Login Successful",
        "register_success" to "Registration Successful",

        // Tabs & Navigation
        "tab_support" to "Support",
        "tab_service" to "Service",
        "home" to "Home",
        "saved" to "Saved",
        "emergency" to "Emergency",
        "chat" to "Chat",
        "profile" to "Profile",

        // Home & Posts
        "empty_posts" to "No post found",
        "empty_saved_posts" to "No saved posts yet",
        "create_post_title" to "Create Post",
        "post_button" to "Post",
        "post_success" to "Post created successfully!",
        "what_on_your_mind" to "Describe what you need help with or offer...",
        "select_city" to "Select City",
        "select_district" to "Select District",
        "select_category" to "Select Category",
        "label_city" to "City",
        "label_district" to "District",
        "label_category" to "Category",
        "fill_all_fields" to "Please fill all fields",
        "comments" to "Comments",
        "share" to "Share",
        "like" to "Like",
        "report" to "Report",
        "hide" to "Hide",
        "post_saved" to "Post saved!",
        "save_post" to "Save post",
        "unsave_post" to "Unsave post",
        "hide_post" to "Hide post",
        "post_hidden" to "Post hidden",
        "report_post" to "Report post",
        "report_success" to "Report submitted successfully",
        "about_user" to "About",

        // Chat List & Detail
        "chat_title" to "Chats",
        "chat_search" to "Search...",
        "chat_all" to "All",
        "chat_unread" to "Unread",
        "chat_groups" to "Groups",
        "chat_active_now" to "Active Now",
        "chat_type_message" to "Type a message...",
        "reply" to "Reply",
        "send" to "Send",
        "no_comments" to "No comments yet",
        "chat_auto_reply" to "Auto reply from bot ",
        "be_first_comment" to "Be the first to comment!",
        "no_messages" to "No messages yet",
        "spam_messages_title" to "Message Requests",
        "spam_messages_subtitle" to "Messages from strangers",
        "no_spam_messages" to "No message requests",
        "messages_count_suffix" to "messages",
        "stranger_chat_warning_title" to "Message Request",
        "stranger_chat_warning_msg" to "This person is not in your friends list. Accept to reply.",
        "btn_accept_chat" to "Accept",
        "btn_decline_chat" to "Decline",
        "msg_sent_friend_request" to "Sent a friend request",
        "msg_start_conversation" to "Started a conversation",

        // Chat Actions
        "delete_chat_menu" to "Delete Conversation",
        "delete_chat_confirm_title" to "Delete this chat?",
        "delete_chat_confirm_msg" to "This copy of the conversation will be permanently deleted from your account. The other person will still see the messages.",
        "stranger_chat_warning" to "This person is not in your friends list.",

        // Friends Management
        "add_new_friend_title" to "Add New Friend",
        "search_by_phone_hint" to "Search by phone number",
        "phone_label" to "Phone Number",
        "results_label" to "Results:",
        "user_not_found" to "User not found",
        "friend_status_friend" to "Friends",
        "friend_status_sent" to "Sent",
        "friend_status_received" to "Accept",
        "btn_accept" to "Accept",
        "btn_decline" to "Decline",
        "btn_add_friend" to "Add Friend",
        "btn_cancel_request" to "Cancel Request",
        "tab_requests" to "Requests",
        "tab_friends" to "Friends",
        "no_friend_requests" to "No friend requests",
        "no_friends_list" to "Friend list is empty",
        "unfriend_title" to "Unfriend",
        "unfriend_confirm_msg" to "Are you sure you want to unfriend %s?",
        "request_friend_msg" to "Wants to be your friend",

        // Profile & Account
        "profile_title" to "Profile",
        "account_settings" to "Account Settings",
        "account_data" to "Account Data",
        "help_support" to "Help & Support",
        "settings" to "Settings",
        "logout" to "Logout",
        "change_avatar" to "Change Avatar",
        "edit_profile" to "Edit Profile",
        "name" to "Name",
        "bio" to "Bio / Status",
        "password_incorrect" to "Password is incorrect",
        "address" to "Address",
        "gender" to "Gender",
        "current_job" to "Current Job",
        "edit_in_settings" to "Edit in Account Settings",
        "edit_address" to "Edit Address",
        "enter_address" to "Enter your address",
        "edit_job" to "Edit Current Job",
        "enter_job" to "Enter your current job",
        "field_empty_error" to "This field cannot be empty",
        "joined_date" to "Member since",
        "not_updated" to "Not updated",
        "hidden_info" to "Hidden",

        // Gender Selection
        "select_gender" to "Select Gender",
        "male" to "Male",
        "female" to "Female",
        "other" to "Other",
        "not_say" to "Prefer not to say",
        "not_update" to "Not Update",

        // Account Settings Specific
        "change_password" to "Change Password",
        "current_password" to "Current Password",
        "new_password" to "New Password",
        "confirm_password" to "Confirm Password",
        "passwords_not_match" to "Passwords do not match",
        "password_length_error" to "Password must be at least 6 characters",
        "verify_password" to "Verify Password",
        "verify_password_msg" to "Please enter your password to change phone number",
        "password_required" to "Password is required",
        "change_phone" to "Change Phone Number",
        "new_phone" to "New Phone Number",
        "phone_required" to "Phone number is required",
        "invalid_phone" to "Invalid phone number",
        "name_empty_error" to "Name cannot be empty",
        "logout_confirm_title" to "Logout Confirmation",
        "logout_confirm_msg" to "Are you sure you want to logout?",
        "avatar_updated" to "Avatar updated!",
        "current_password_incorrect" to "Current password is incorrect",
        "password_not_strong" to "New password is not strong enough (Must have uppercase, lowercase, number, and > 8 characters)",
        "change_password_successful" to "Password changed successfully!",
        "change_password_failed" to "Password change failed.",
        "change_phone_successful" to "Phone number changed successfully!",

        // Other Profile
        "other_profile_title" to "User Profile",
        "rating_score" to "Community Rating",
        "reviews" to "Reviews",
        "message" to "Message",
        "friends" to "Friends",
        "friend_accept" to "Accept",
        "no_bio" to "No bio yet",

        // Help & Support
        "need_help" to "Need Help?",
        "contact_support_msg" to "Contact our support team for assistance",
        "contact_info" to "Contact Information",
        "phone_copied" to "Phone number copied!",
        "email_copied" to "Email address copied!",
        "support_hours" to "Support Hours",
        "hours_detail" to "Monday - Friday: 8:00 AM - 8:00 PM\nSaturday - Sunday: 9:00 AM - 6:00 PM",

        // Settings Screen
        "language" to "Language",
        "dark_mode" to "Dark Mode",
        "light_mode" to "Light Mode",
        "on" to "On",
        "off" to "Off",
        "block_list" to "Block List",
        "users" to "users",
        "no_blocked_users" to "No blocked users",
        "unblock" to "Unblock",
        "delete_account" to "Delete Account",
        "delete_account_title" to "Delete Account",
        "delete_warning_desc" to "Warning: This action is irreversible. All your data, messages, and account information will be permanently deleted.",
        "enter_password_continue" to "Enter password to continue",
        "type_delete" to "Type 'DELETE' to confirm",
        "delete_forever" to "Delete Forever",
        "saved_posts" to "Saved_posts",
        // --- NEW KEYS FOR BLOCKING & ERRORS ---
        "block_user" to "Block User",
        "block_user_title" to "Block this user?",
        "block_user_msg" to "They won't be able to find your profile or send you messages. You can unblock them in Settings.",
        "block" to "Block",
        "user_unavailable" to "User not found or unavailable.",
        "blocked_success" to "User blocked.",
        "error_blocking" to "Error blocking user: ",
        "error_friend_request" to "Error sending request: ",
        "error_cancel_request" to "Error canceling request: ",
        "error_create_chat" to "Cannot create conversation",
        "user_inactive" to "This user is no longer active",
        "blocked_msg_error" to "You cannot message this user.",

        // --- REVIEW & RATING ---
        "rating_reviews" to "Ratings & Reviews",
        "see_reviews" to "See Reviews",
        "write_review" to "Write a review",
        "write_review_hint" to "Share your experience...",
        "submit_review" to "Submit",
        "delete_review" to "Delete Rating",
        "review_empty_error" to "Please select stars to rate.",
        "not_enough_messages" to "You need to exchange at least 10 messages to rate this user.",
        "load_more_reviews" to "Load more reviews",
        "no_reviews_yet" to "No reviews yet.",
        "your_rating" to "Your Rating",
        "delete_review_confirm" to "Delete your review?",

        // --- REPORT DIALOG (POSTS & USERS) ---
        "report_title" to "Report Post",
        "report_user_title" to "Report User",
        "report_reason" to "Reason",
        "select_reason" to "Select a reason",

        // Reasons for POSTS
        "report_fraud" to "Fraud or Scam",
        "report_inappropriate" to "Inappropriate Content",
        "report_trading" to "Prohibited Items/Trading",
        "report_offensive" to "Hate Speech or Offensive",
        "report_misinformation" to "False Information",

        // Reasons for USERS (Mới)
        "report_reason_spam" to "Spam or Scam",
        "report_reason_harassment" to "Harassment or Bullying",
        "report_reason_fake" to "Fake Account",
        "report_reason_inappropriate" to "Inappropriate Content",
        "report_reason_other" to "Other",

        "report_other" to "Other",
        "report_other_hint" to "Please specify the reason...",
        "report_select_reason_required" to "Please select a reason",
        "report_description" to "Description",
        "report_description_hint" to "Provide more details about the issue (Optional)",
        "report_cancel" to "Cancel",
        "report_submit" to "Submit",
        "report_submitted_success" to "Report submitted. Thank you!",
        "report_user" to "Report User",
        "report_duplicate_post" to "You have already reported this post", // Đổi key cũ cho rõ nghĩa
        "report_duplicate_user" to "You have already reported this user", // Thêm key mới
        "report_error" to "Error sending report: ",
        "user_unavailable" to "User unavailable or blocked",
        "user_inactive" to "This account is currently inactive",
        "blocked_msg_error" to "You cannot send messages to this user",
        "error" to "Error",
        "tab_everyone" to "Everyone",
        "tab_foryou" to "For You",
        "tab_saved" to "Saved",
        "tab_support" to "Support",
        "tab_service" to "Service",
        "empty_saved_posts" to "No saved posts yet",
        "empty_posts" to "No posts found",
        "cancel" to "Cancel",
        "save" to "Save",
        "confirm" to "Confirm",
        "back" to "Back",
        "close" to "Close",
        "next" to "Next",
        "edit" to "Edit",
        "copy" to "Copy",
        "yes" to "Yes",
        "no" to "No",
        "apply" to "Apply",
        "loading" to "Loading...",
        "error" to "Error",
        "success" to "Success",
        "delete" to "Delete",
        "search" to "Search",
        "filter" to "Filter",
        "clear_filter" to "Clear Filter",
        "select_city" to "Select City",
        "select_district" to "Select District",
        "select_category" to "Select Category",
        "all_locations" to "All Locations",
        "all_categories" to "All Categories",
        "what_on_your_mind" to "What's on your mind?",
        "post_button" to "Post",
        "post_success" to "Posted successfully!",
        "login" to "Login",
        "register" to "Register",
        "logout" to "Logout",
        "profile_title" to "Profile",
        "chat_title" to "Messages",
        "notifications" to "Notifications",
        // Notifications Screen
        "notifications" to "Notifications",
        "mark_all_read" to "Mark all as read",
        "social" to "Social",
        "system" to "System",
        "clear_all" to "Clear all",
        "no_notifications" to "No notifications yet",
        "social_empty_msg" to "Interactions like likes, comments, and friend requests will appear here.",
        "emergency_empty_msg" to "System alerts and emergency updates will be shown here.",
        "friend_reject" to "Reject",
        "Warning" to "Warning",
        "Announcement" to "Announcement",

        // Notification Types
        "notif_liked_post" to "liked your post",
        "notif_liked_comment" to "liked your comment",
        "notif_commented" to "commented on your post",
        "notif_replied" to "replied to your comment",
        "notif_friend_request" to "sent you a friend request",
        "notif_sos_accepted" to "accepted your support request",
        "notif_emergency_approved" to "Your emergency request has been approved",
        "notif_emergency_rejected" to "Your emergency request has been rejected",

        // Time ago labels
        "cat_repair" to "Repair",
        "cat_cleaning" to "Cleaning",
        "cat_tutor" to "Tutor",
        "cat_delivery" to "Delivery",
        "cat_pet_care" to "Pet Care",
        "cat_beauty" to "Beauty/Spa",
        "cat_it_support" to "IT Support",
        "cat_driver" to "Driver",
        "cat_emergency" to "Emergency Rescue",
        "cat_medical" to "Medical Help",
        "cat_lost_found" to "Lost & Found",
        "cat_donation" to "Donation",
        "cat_transport_help" to "Transport Help",
        "cat_volunteer" to "Volunteer",
        "cat_food_water" to "Food & Water",
        // --- CITIES (ENGLISH - NO ACCENT) ---
        "city_hcm" to "Ho Chi Minh City",
        "city_hn" to "Ha Noi",
        "city_dn" to "Da Nang",
        "city_hp" to "Hai Phong",
        "city_ct" to "Can Tho",
        "city_ag" to "An Giang",
        "city_brvt" to "Ba Ria - Vung Tau",
        "city_bl" to "Bac Lieu",
        "city_bk" to "Bac Kan",
        "city_bg" to "Bac Giang",
        "city_bn" to "Bac Ninh",
        "city_btre" to "Ben Tre",
        "city_bd" to "Binh Duong",
        "city_bdi" to "Binh Dinh",
        "city_bp" to "Binh Phuoc",
        "city_bth" to "Binh Thuan",
        "city_cm" to "Ca Mau",
        "city_cb" to "Cao Bang",
        "city_dl" to "Dak Lak",
        "city_dno" to "Dak Nong",
        "city_db" to "Dien Bien",
        "city_dnai" to "Dong Nai",
        "city_dt" to "Dong Thap",
        "city_gl" to "Gia Lai",
        "city_hg" to "Ha Giang",
        "city_hnam" to "Ha Nam",
        "city_ht" to "Ha Tinh",
        "city_hdu" to "Hai Duong",
        "city_hgi" to "Hau Giang",
        "city_hb" to "Hoa Binh",
        "city_hy" to "Hung Yen",
        "city_kh" to "Khanh Hoa",
        "city_kg" to "Kien Giang",
        "city_kt" to "Kon Tum",
        "city_lc" to "Lai Chau",
        "city_ld" to "Lam Dong",
        "city_ls" to "Lang Son",
        "city_lca" to "Lao Cai",
        "city_la" to "Long An",
        "city_nd" to "Nam Dinh",
        "city_na" to "Nghe An",
        "city_nb" to "Ninh Binh",
        "city_nt" to "Ninh Thuan",
        "city_pt" to "Phu Tho",
        "city_py" to "Phu Yen",
        "city_qb" to "Quang Binh",
        "city_qnam" to "Quang Nam",
        "city_qng" to "Quang Ngai",
        "city_qn" to "Quang Ninh",
        "city_qt" to "Quang Tri",
        "city_st" to "Soc Trang",
        "city_sl" to "Son La",
        "city_tn" to "Tay Ninh",
        "city_tb" to "Thai Binh",
        "city_tng" to "Thai Nguyen",
        "city_th" to "Thanh Hoa",
        "city_hue" to "Thua Thien Hue",
        "city_tg" to "Tien Giang",
        "city_tv" to "Tra Vinh",
        "city_tq" to "Tuyen Quang",
        "city_vl" to "Vinh Long",
        "city_vt" to "Vinh Phuc",
        "city_yb" to "Yen Bai",
        //Các Quận/Huyện
        "dist_long_xuyen" to "Long Xuyen",
        "dist_chau_doc" to "Chau Doc",
        "dist_tan_chau" to "Tan Chau",
        "dist_quy_nhon" to "Quy Nhon",
        "dist_an_nhon" to "An Nhon",
        "dist_hoai_nhon" to "Hoai Nhon",
        "dist_phan_thiet" to "Phan Thiet",
        "dist_la_gi" to "La Gi",
        "dist_tuy_phong" to "Tuy Phong",
        "dist_ca_mau_tp" to "Ca Mau City",
        "dist_nam_can" to "Nam Can",
        "dist_u_minh" to "U Minh",
        "dist_buon_ma_thuot" to "Buon Ma Thuot",
        "dist_buon_ho" to "Buon Ho",
        "dist_cu_mgar" to "Cu M'gar",
        "dist_cao_lanh" to "Cao Lanh",
        "dist_sa_dec" to "Sa Dec",
        "dist_hong_ngu" to "Hong Ngu",
        "dist_pleiku" to "Pleiku",
        "dist_an_khe" to "An Khe",
        "dist_ayun_pa" to "Ayun Pa",
        "dist_phu_ly" to "Phu Ly",
        "dist_duy_tien" to "Duy Tien",
        "dist_ha_tinh_tp" to "Ha Tinh City",
        "dist_hong_linh" to "Hong Linh",
        "dist_ky_anh" to "Ky Anh",
        "dist_hai_duong_tp" to "Hai Duong City",
        "dist_chi_linh" to "Chi Linh",
        "dist_kinh_mon" to "Kinh Mon",
        "dist_hung_yen_tp" to "Hung Yen City",
        "dist_my_hao" to "My Hao",
        "dist_van_giang" to "Van Giang",
        "dist_rach_gia" to "Rach Gia",
        "dist_ha_tien" to "Ha Tien",
        "dist_phu_quoc" to "Phu Quoc",
        "dist_lang_son_tp" to "Lang Son City",
        "dist_huu_lung" to "Huu Lung",
        "dist_lao_cai_tp" to "Lao Cai City",
        "dist_sa_pa" to "Sa Pa",
        "dist_nam_dinh_tp" to "Nam Dinh City",
        "dist_giao_thuy" to "Giao Thuy",
        "dist_hai_hau" to "Hai Hau",
        "dist_vinh" to "Vinh",
        "dist_cua_lo" to "Cua Lo",
        "dist_hoang_mai_na" to "Hoang Mai",
        "dist_dien_chau" to "Dien Chau",
        "dist_ninh_binh_tp" to "Ninh Binh City",
        "dist_tam_diep" to "Tam Diep",
        "dist_viet_tri" to "Viet Tri",
        "dist_phu_tho_tx" to "Phu Tho Town",
        "dist_tuy_hoa" to "Tuy Hoa",
        "dist_song_cau" to "Song Cau",
        "dist_dong_hoa" to "Dong Hoa",
        "dist_dong_hoi" to "Dong Hoi",
        "dist_ba_don" to "Ba Don",
        "dist_tam_ky" to "Tam Ky",
        "dist_hoi_an" to "Hoi An",
        "dist_dien_ban" to "Dien Ban",
        "dist_quang_ngai_tp" to "Quang Ngai City",
        "dist_duc_pho" to "Duc Pho",
        "dist_tay_ninh_tp" to "Tay Ninh City",
        "dist_hoa_thanh" to "Hoa Thanh",
        "dist_trang_bang" to "Trang Bang",
        "dist_thai_binh_tp" to "Thai Binh City",
        "dist_thai_nguyen_tp" to "Thai Nguyen City",
        "dist_song_cong" to "Song Cong",
        "dist_pho_yen" to "Pho Yen",
        "dist_thanh_hoa_tp" to "Thanh Hoa City",
        "dist_sam_son" to "Sam Son",
        "dist_bim_son" to "Bim Son",
        "dist_vinh_long_tp" to "Vinh Long City",
        "dist_binh_minh" to "Binh Minh",
        "dist_vinh_yen" to "Vinh Yen",
        "dist_phuc_yen" to "Phuc Yen",

        // HCM & HANOI (Cũ)
        "dist_1" to "District 1",
        "dist_3" to "District 3",
        "dist_4" to "District 4",
        "dist_5" to "District 5",
        "dist_6" to "District 6",
        "dist_7" to "District 7",
        "dist_8" to "District 8",
        "dist_10" to "District 10",
        "dist_11" to "District 11",
        "dist_12" to "District 12",
        "dist_binh_thanh" to "Binh Thanh",
        "dist_go_vap" to "Go Vap",
        "dist_phu_nhuan" to "Phu Nhuan",
        "dist_tan_binh" to "Tan Binh",
        "dist_tan_phu" to "Tan Phu",
        "dist_thu_duc" to "Thu Duc City",
        "dist_binh_tan" to "Binh Tan",
        "dist_cu_chi" to "Cu Chi",
        "dist_hoc_mon" to "Hoc Mon",
        "dist_binh_chanh" to "Binh Chanh",
        "dist_nha_be" to "Nha Be",
        "dist_ba_dinh" to "Ba Dinh",
        "dist_hoan_kiem" to "Hoan Kiem",
        "dist_tay_ho" to "Tay Ho",
        "dist_cau_giay" to "Cau Giay",
        "dist_dong_da" to "Dong Da",
        "dist_hai_ba_trung" to "Hai Ba Trung",
        "dist_hoang_mai" to "Hoang Mai",
        "dist_thanh_xuan" to "Thanh Xuan",
        "dist_long_bien" to "Long Bien",
        "dist_nam_tu_liem" to "Nam Tu Liem",
        "dist_bac_tu_liem" to "Bac Tu Liem",
        "dist_ha_dong" to "Ha Dong",
        "dist_hai_chau" to "Hai Chau",
        "dist_thanh_khe" to "Thanh Khe",
        "dist_son_tra" to "Son Tra",
        "dist_ngu_hanh_son" to "Ngu Hanh Son",
        "dist_lien_chieu" to "Lien Chieu",
        "dist_cam_le" to "Cam Le",
        "dist_thu_dau_mot" to "Thu Dau Mot",
        "dist_di_an" to "Di An",
        "dist_thuan_an" to "Thuan An",
        "dist_ben_cat" to "Ben Cat",
        "dist_tan_uyen" to "Tan Uyen",
        "dist_bien_hoa" to "Bien Hoa",
        "dist_long_khanh" to "Long Khanh",
        "dist_long_thanh" to "Long Thanh",
        "dist_nhon_trach" to "Nhon Trach",
        "dist_trang_bom" to "Trang Bom",
        "dist_vung_tau" to "Vung Tau",
        "dist_ba_ria" to "Ba Ria",
        "dist_phu_my" to "Phu My",
        "dist_da_lat" to "Da Lat",
        "dist_bao_loc" to "Bao Loc",
        "dist_duc_trong" to "Duc Trong",
        "dist_nha_trang" to "Nha Trang",
        "dist_cam_ranh" to "Cam Ranh",
        "dist_ninh_hoa" to "Ninh Hoa",
        "dist_hue" to "Hue City",
        "dist_huong_thuy" to "Huong Thuy",
        "dist_huong_tra" to "Huong Tra",
        "dist_bac_ninh_tp" to "Bac Ninh City",
        "dist_tu_son" to "Tu Son",
        "dist_yen_phong" to "Yen Phong",
        "dist_ha_long" to "Ha Long",
        "dist_mong_cai" to "Mong Cai",
        "dist_cam_pha" to "Cam Pha",
        "dist_ninh_kieu" to "Ninh Kieu",
        "dist_binh_thuy" to "Binh Thuy",
        "dist_cai_rang" to "Cai Rang",
        "dist_hong_bang" to "Hong Bang",
        "dist_ngo_quyen" to "Ngo Quyen",
        "dist_le_chan" to "Le Chan",
        "dist_hoang_sa" to "Hoang Sa", // Da Nang
        "dist_truong_sa" to "Truong Sa", // Khanh Hoa
        "dist_con_dao" to "Con Dao", // Ba Ria - Vung Tau
        "dist_phu_quy" to "Phu Quy", // Binh Thuan
        "dist_ly_son" to "Ly Son", // Quang Ngai
        "dist_bach_long_vi" to "Bach Long Vi", // Hai Phong
        "dist_cat_hai" to "Cat Hai", // Hai Phong
        "dist_con_co" to "Con Co", // Quang Tri
        "dist_kien_hai" to "Kien Hai", // Kien Giang
        "dist_co_to" to "Co To", // Quang Ninh
        "dist_van_don" to "Van Don", // Quang Ninh
        "dist_phu_quoc" to "Phu Quoc City", // Updated status (if not already set)

// ==============================================================================
// --- ADDED: NORTHERN VIETNAM (MISSING DISTRICTS) ---
// ==============================================================================

// --- Hanoi (Extended) ---
        "dist_son_tay" to "Son Tay Town",
        "dist_ba_vi" to "Ba Vi",
        "dist_chuong_my" to "Chuong My",
        "dist_dan_phuong" to "Dan Phuong",
        "dist_dong_anh" to "Dong Anh",
        "dist_gia_lam" to "Gia Lam",
        "dist_hoai_duc" to "Hoai Duc",
        "dist_me_linh" to "Me Linh",
        "dist_my_duc" to "My Duc",
        "dist_phu_xuyen" to "Phu Xuyen",
        "dist_phuc_tho" to "Phuc Tho",
        "dist_quoc_oai" to "Quoc Oai",
        "dist_soc_son" to "Soc Son",
        "dist_thach_that" to "Thach That",
        "dist_thanh_oai" to "Thanh Oai",
        "dist_thanh_tri" to "Thanh Tri",
        "dist_thuong_tin" to "Thuong Tin",
        "dist_ung_hoa" to "Ung Hoa",

// --- Hai Phong (Extended) ---
        "dist_kien_an" to "Kien An",
        "dist_do_son" to "Do Son",
        "dist_duong_kinh" to "Duong Kinh",
        "dist_an_duong" to "An Duong",
        "dist_an_lao" to "An Lao",
        "dist_kien_thuy" to "Kien Thuy",
        "dist_thuy_nguyen" to "Thuy Nguyen",
        "dist_tien_lang" to "Tien Lang",
        "dist_vinh_bao" to "Vinh Bao",

// --- Quang Ninh (Extended) ---
        "dist_uong_bi" to "Uong Bi City",
        "dist_dong_trieu" to "Dong Trieu City",
        "dist_quang_yen" to "Quang Yen Town",
        "dist_ba_che" to "Ba Che",
        "dist_binh_lieu" to "Binh Lieu",
        "dist_dam_ha" to "Dam Ha",
        "dist_hai_ha" to "Hai Ha",
        "dist_tien_yen" to "Tien Yen",

// --- Ha Giang (Full) ---
        "dist_dong_van" to "Dong Van",
        "dist_meo_vac" to "Meo Vac",
        "dist_yen_minh" to "Yen Minh",
        "dist_quan_ba" to "Quan Ba",
        "dist_vi_xuyen" to "Vi Xuyen",
        "dist_bac_me" to "Bac Me",
        "dist_hoang_su_phi" to "Hoang Su Phi",
        "dist_xin_man" to "Xin Man",
        "dist_bac_quang" to "Bac Quang",
        "dist_quang_binh" to "Quang Binh",

// --- Cao Bang (Full) ---
        "dist_bao_lam" to "Bao Lam",
        "dist_bao_lac" to "Bao Lac",
        "dist_ha_quang" to "Ha Quang",
        "dist_trung_khanh" to "Trung Khanh",
        "dist_ha_lang" to "Ha Lang",
        "dist_quang_hoa" to "Quang Hoa",
        "dist_hoa_an" to "Hoa An",
        "dist_nguyen_binh" to "Nguyen Binh",
        "dist_thach_an" to "Thach An",

// --- Lao Cai (Extended) ---
        "dist_bat_xat" to "Bat Xat",
        "dist_muong_khuong" to "Muong Khuong",
        "dist_si_ma_cai" to "Si Ma Cai",
        "dist_bac_ha" to "Bac Ha",
        "dist_bao_thang" to "Bao Thang",
        "dist_bao_yen" to "Bao Yen",
        "dist_van_ban" to "Van Ban",

// --- Dien Bien (Full) ---
        "dist_muong_lay" to "Muong Lay Town",
        "dist_dien_bien_dong" to "Dien Bien Dong",
        "dist_muong_ang" to "Muong Ang",
        "dist_muong_nhe" to "Muong Nhe",
        "dist_muong_cha" to "Muong Cha",
        "dist_tua_chua" to "Tua Chua",
        "dist_tuan_giao" to "Tuan Giao",
        "dist_nam_po" to "Nam Po",

// ==============================================================================
// --- ADDED: CENTRAL VIETNAM (MISSING DISTRICTS) ---
// ==============================================================================

// --- Thanh Hoa (Extended) ---
        "dist_nghi_son" to "Nghi Son Town",
        "dist_ba_thuoc" to "Ba Thuoc",
        "dist_cam_thuy" to "Cam Thuy",
        "dist_dong_son" to "Dong Son",
        "dist_ha_trung" to "Ha Trung",
        "dist_hau_loc" to "Hau Loc",
        "dist_hoang_hoa" to "Hoang Hoa",
        "dist_lang_chanh" to "Lang Chanh",
        "dist_muong_lat" to "Muong Lat",
        "dist_nga_son" to "Nga Son",
        "dist_ngoc_lac" to "Ngoc Lac",
        "dist_nhu_thanh" to "Nhu Thanh",
        "dist_nhu_xuan" to "Nhu Xuan",
        "dist_nong_cong" to "Nong Cong",
        "dist_quan_hoa" to "Quan Hoa",
        "dist_quan_son" to "Quan Son",
        "dist_quang_xuong" to "Quang Xuong",
        "dist_thach_thanh" to "Thach Thanh",
        "dist_thieu_hoa" to "Thieu Hoa",
        "dist_tho_xuan" to "Tho Xuan",
        "dist_thuong_xuan" to "Thuong Xuan",
        "dist_trieu_son" to "Trieu Son",
        "dist_vinh_loc" to "Vinh Loc",
        "dist_yen_dinh" to "Yen Dinh",

// --- Nghe An (Extended) ---
        "dist_thai_hoa" to "Thai Hoa Town",
        "dist_anh_son" to "Anh Son",
        "dist_con_cuong" to "Con Cuong",
        "dist_do_luong" to "Do Luong",
        "dist_hung_nguyen" to "Hung Nguyen",
        "dist_ky_son" to "Ky Son",
        "dist_nam_dan" to "Nam Dan",
        "dist_nghi_loc" to "Nghi Loc",
        "dist_nghia_dan" to "Nghia Dan",
        "dist_que_phong" to "Que Phong",
        "dist_quy_chau" to "Quy Chau",
        "dist_quy_hop" to "Quy Hop",
        "dist_quynh_luu" to "Quynh Luu",
        "dist_tan_ky" to "Tan Ky",
        "dist_thanh_chuong" to "Thanh Chuong",
        "dist_tuong_duong" to "Tuong Duong",
        "dist_yen_thanh" to "Yen Thanh",

// --- Ha Tinh (Extended) ---
        "dist_can_loc" to "Can Loc",
        "dist_cam_xuyen" to "Cam Xuyen",
        "dist_huong_khe" to "Huong Khe",
        "dist_huong_son" to "Huong Son",
        "dist_loc_ha" to "Loc Ha",
        "dist_nghi_xuan" to "Nghi Xuan",
        "dist_thach_ha" to "Thach Ha",
        "dist_vu_quang" to "Vu Quang",
        "dist_duc_tho" to "Duc Tho",

// --- Quang Binh (Extended) ---
        "dist_bo_trach" to "Bo Trach",
        "dist_le_thuy" to "Le Thuy",
        "dist_minh_hoa" to "Minh Hoa",
        "dist_quang_ninh_qb" to "Quang Ninh (QB)",
        "dist_quang_trach" to "Quang Trach",
        "dist_tuyen_hoa" to "Tuyen Hoa",

// --- Quang Tri (Extended) ---
        "dist_quang_tri_tx" to "Quang Tri Town",
        "dist_cam_lo" to "Cam Lo",
        "dist_da_krong" to "Da Krong",
        "dist_gio_linh" to "Gio Linh",
        "dist_hai_lang" to "Hai Lang",
        "dist_huong_hoa" to "Huong Hoa",
        "dist_trieu_phong" to "Trieu Phong",
        "dist_vinh_linh" to "Vinh Linh",

// --- Da Nang (Extended) ---
        "dist_hoa_vang" to "Hoa Vang",



// --- Ho Chi Minh City (Extended) ---
        "dist_can_gio" to "Can Gio",

// --- Can Tho (Extended) ---
        "dist_o_mon" to "O Mon",
        "dist_thot_not" to "Thot Not",
        "dist_co_do" to "Co Do",
        "dist_phong_dien" to "Phong Dien",
        "dist_thoi_lai" to "Thoi Lai",
        "dist_vinh_thanh_ct" to "Vinh Thanh",

// --- Kien Giang (Extended) ---
        "dist_an_bien" to "An Bien",
        "dist_an_minh" to "An Minh",
        "dist_chau_thanh_kg" to "Chau Thanh (KG)",
        "dist_giang_thanh" to "Giang Thanh",
        "dist_giong_rieng" to "Giong Rieng",
        "dist_go_quao" to "Go Quao",
        "dist_hon_dat" to "Hon Dat",
        "dist_kien_luong" to "Kien Luong",
        "dist_tan_hiep" to "Tan Hiep",
        "dist_u_minh_thuong" to "U Minh Thuong",
        "dist_vinh_thuan" to "Vinh Thuan",

// --- Dong Nai (Extended) ---
        "dist_cam_my" to "Cam My",
        "dist_dinh_quan" to "Dinh Quan",
        "dist_tan_phu_dn" to "Tan Phu (DN)",
        "dist_thong_nhat" to "Thong Nhat",
        "dist_vinh_cuu" to "Vinh Cuu",
        "dist_xuan_loc" to "Xuan Loc",

// --- Binh Duong (Extended) ---
        "dist_bac_tan_uyen" to "Bac Tan Uyen",
        "dist_bau_bang" to "Bau Bang",
        "dist_dau_tieng" to "Dau Tieng",
        "dist_phu_giao" to "Phu Giao",

    )

    val VI = mapOf(
        "email_exists_error" to "Email này đã được đăng ký tài khoản.",
        "unknown_error" to "Đã xảy ra lỗi không xác định.",
        // Common
        "app_name" to "LocaSOS",
        "cancel" to "Hủy",
        "save" to "Lưu",
        "confirm" to "Xác nhận",
        "back" to "Quay lại",
        "close" to "Đóng",
        "next" to "Tiếp theo",
        "edit" to "Sửa",
        "copy" to "Sao chép",
        "yes" to "Có",
        "no" to "Không",
        "apply" to "Áp dụng",
        "loading" to "Đang tải...",
        "error" to "Lỗi",
        "success" to "Thành công",
        "delete" to "Xóa",
        "search" to "Tìm kiếm",
        "saved_posts" to "Đã lưu",
        // Auth
        "login" to "Đăng nhập",
        "register" to "Đăng ký",
        "forgot_password" to "Quên mật khẩu",
        "email" to "Email",
        "password" to "Mật khẩu",
        "phone_number" to "Số điện thoại",
        "full_name" to "Họ và tên",
        "login_success" to "Đăng nhập thành công",
        "register_success" to "Đăng ký thành công",

        // Tabs & Navigation
        "tab_support" to "Hỗ trợ",
        "tab_service" to "Dịch vụ",
        "home" to "Trang chủ",
        "saved" to "Đã lưu",
        "emergency" to "Khẩn cấp",
        "chat" to "Tin nhắn",
        "profile" to "Cá nhân",

        // Home & Posts
        "empty_posts" to "Chưa có bài viết nào",
        "empty_saved_posts" to "Chưa có bài viết đã lưu",
        "create_post_title" to "Tạo bài viết",
        "post_button" to "Đăng",
        "post_success" to "Đã đăng bài viết!",
        "what_on_your_mind" to "Mô tả việc bạn cần giúp hoặc cung cấp...",
        "select_city" to "Chọn Thành phố",
        "select_district" to "Chọn Quận/Huyện",
        "select_category" to "Chọn Danh mục",
        "label_city" to "Thành phố",
        "label_district" to "Quận/Huyện",
        "label_category" to "Danh mục",
        "fill_all_fields" to "Vui lòng điền đầy đủ thông tin",
        "comments" to "Bình luận",
        "share" to "Chia sẻ",
        "like" to "Thích",
        "report" to "Báo cáo",
        "hide" to "Ẩn",
        "post_saved" to "Đã lưu bài viết!",
        "save_post" to "Lưu bài viết",
        "unsave_post" to "Bỏ lưu bài viết",
        "hide_post" to "Ẩn bài viết",
        "post_hidden" to "Đã ẩn bài viết",
        "report_post" to "Báo cáo bài viết",
        "report_success" to "Gửi báo cáo thành công",
        "about_user" to "Về",

        // Chat List & Detail
        "chat_title" to "Tin nhắn",
        "chat_search" to "Tìm kiếm...",
        "chat_all" to "Tất cả",
        "chat_unread" to "Chưa đọc",
        "chat_groups" to "Nhóm",
        "chat_active_now" to "Đang hoạt động",
        "chat_type_message" to "Nhập tin nhắn...",
        "reply" to "Trả lời",
        "send" to "Gửi",
        "no_comments" to "Chưa có bình luận",
        "chat_auto_reply" to "Trả lời tự động từ bot ",
        "be_first_comment" to "Hãy là người đầu tiên bình luận!",
        "no_messages" to "Chưa có tin nhắn",
        "spam_messages_title" to "Tin nhắn chờ",
        "spam_messages_subtitle" to "Tin nhắn từ người lạ",
        "no_spam_messages" to "Không có tin nhắn chờ nào",
        "messages_count_suffix" to "tin nhắn",
        "stranger_chat_warning_title" to "Tin nhắn chờ",
        "stranger_chat_warning_msg" to "Người này không nằm trong danh sách bạn bè. Chấp nhận để trả lời.",
        "btn_accept_chat" to "Chấp nhận",
        "btn_decline_chat" to "Từ chối",
        "msg_sent_friend_request" to "Đã gửi lời mời kết bạn",
        "msg_start_conversation" to "Bắt đầu cuộc trò chuyện",

        // Chat Actions
        "delete_chat_menu" to "Xóa đoạn chat",
        "delete_chat_confirm_title" to "Xóa đoạn chat?",
        "delete_chat_confirm_msg" to "Bản sao cuộc trò chuyện này sẽ bị xóa vĩnh viễn khỏi tài khoản của bạn. Người kia vẫn sẽ nhìn thấy tin nhắn.",
        "stranger_chat_warning" to "Người này không nằm trong danh sách bạn bè của bạn.",

        // Friends Management
        "add_new_friend_title" to "Thêm bạn mới",
        "search_by_phone_hint" to "Tìm kiếm bằng số điện thoại",
        "phone_label" to "Số điện thoại",
        "results_label" to "Kết quả:",
        "user_not_found" to "Không tìm thấy người dùng",
        "friend_status_friend" to "Bạn bè",
        "friend_status_sent" to "Đã gửi",
        "friend_status_received" to "Chấp nhận",
        "btn_accept" to "Chấp nhận",
        "btn_decline" to "Từ chối",
        "btn_add_friend" to "Kết bạn",
        "btn_cancel_request" to "Hủy lời mời",
        "tab_requests" to "Lời mời",
        "tab_friends" to "Bạn bè",
        "no_friend_requests" to "Không có lời mời nào",
        "no_friends_list" to "Danh sách bạn bè trống",
        "unfriend_title" to "Hủy kết bạn",
        "unfriend_confirm_msg" to "Bạn có chắc chắn muốn hủy kết bạn với %s không?",
        "request_friend_msg" to "Muốn kết bạn với bạn",

        // Profile & Account
        "profile_title" to "Hồ sơ",
        "account_settings" to "Cài đặt tài khoản",
        "account_data" to "Dữ liệu cá nhân",
        "help_support" to "Trợ giúp & Hỗ trợ",
        "settings" to "Cài đặt",
        "logout" to "Đăng xuất",
        "change_avatar" to "Đổi ảnh đại diện",
        "edit_profile" to "Chỉnh sửa hồ sơ",
        "name" to "Tên hiển thị",
        "bio" to "Tiểu sử",
        "password_incorrect" to "Mật khẩu không đúng",
        "address" to "Địa chỉ",
        "gender" to "Giới tính",
        "current_job" to "Công việc hiện tại",
        "edit_in_settings" to "Chỉnh sửa trong Cài đặt tài khoản",
        "edit_address" to "Sửa địa chỉ",
        "enter_address" to "Nhập địa chỉ của bạn",
        "edit_job" to "Sửa công việc hiện tại",
        "enter_job" to "Nhập công việc hiện tại",
        "field_empty_error" to "Trường này không được để trống",
        "joined_date" to "Thành viên LocaSOS",
        "not_updated" to "Chưa cập nhật",
        "hidden_info" to "Ẩn",

        // Gender Selection
        "select_gender" to "Chọn giới tính",
        "male" to "Nam",
        "female" to "Nữ",
        "other" to "Khác",
        "not_say" to "Không muốn tiết lộ",
        "not_update" to "Chưa cập nhật",

        // Account Settings Specific
        "change_password" to "Đổi mật khẩu",
        "current_password" to "Mật khẩu hiện tại",
        "new_password" to "Mật khẩu mới",
        "confirm_password" to "Xác nhận mật khẩu",
        "passwords_not_match" to "Mật khẩu không khớp",
        "password_length_error" to "Mật khẩu phải có ít nhất 6 ký tự",
        "verify_password" to "Xác thực mật khẩu",
        "verify_password_msg" to "Vui lòng nhập mật khẩu để đổi số điện thoại",
        "password_required" to "Vui lòng nhập mật khẩu",
        "change_phone" to "Đổi số điện thoại",
        "new_phone" to "Số điện thoại mới",
        "phone_required" to "Vui lòng nhập số điện thoại",
        "invalid_phone" to "Số điện thoại không hợp lệ",
        "name_empty_error" to "Tên không được để trống",
        "logout_confirm_title" to "Xác nhận đăng xuất",
        "logout_confirm_msg" to "Bạn có chắc chắn muốn đăng xuất?",
        "avatar_updated" to "Đã cập nhật ảnh đại diện!",
        "current_password_incorrect" to "Mật khẩu hiện tại không đúng",
        "password_not_strong" to "Mật khẩu mới không đủ mạnh (Cần chữ hoa, thường, số và > 8 ký tự)",
        "change_password_successful" to "Đổi mật khẩu thành công!",
        "change_password_failed" to "Đổi mật khẩu thất bại.",
        "change_phone_successful" to "Đổi số điện thoại thành công!",

        // Other Profile
        "other_profile_title" to "Hồ sơ người dùng",
        "rating_score" to "Đánh giá cộng đồng",
        "reviews" to "Đánh giá",
        "message" to "Nhắn tin",
        "friends" to "Bạn bè",
        "friend_accept" to "Chấp nhận",
        "no_bio" to "Chưa có giới thiệu",

        // Help & Support
        "need_help" to "Cần trợ giúp?",
        "contact_support_msg" to "Liên hệ đội ngũ hỗ trợ để được giúp đỡ",
        "contact_info" to "Thông tin liên hệ",
        "phone_copied" to "Đã sao chép số điện thoại!",
        "email_copied" to "Đã sao chép địa chỉ email!",
        "support_hours" to "Giờ làm việc",
        "hours_detail" to "Thứ 2 - Thứ 6: 8:00 Sáng - 8:00 Tối\nThứ 7 - Chủ Nhật: 9:00 Sáng - 6:00 Tối",

        // Settings Screen
        "language" to "Ngôn ngữ",
        "dark_mode" to "Chế độ tối",
        "light_mode" to "Chế độ sáng",
        "on" to "Bật",
        "off" to "Tắt",
        "block_list" to "Danh sách chặn",
        "users" to "người dùng",
        "no_blocked_users" to "Chưa chặn ai",
        "unblock" to "Bỏ chặn",
        "delete_account" to "Xóa tài khoản",
        "delete_account_title" to "Xóa tài khoản",
        "delete_warning_desc" to "Cảnh báo: Hành động này không thể hoàn tác. Tất cả dữ liệu, tin nhắn và thông tin tài khoản sẽ bị xóa vĩnh viễn.",
        "enter_password_continue" to "Nhập mật khẩu để tiếp tục",
        "type_delete" to "Nhập 'DELETE' để xác nhận",
        "delete_forever" to "Xóa vĩnh viễn",

        // --- NEW KEYS FOR BLOCKING & ERRORS ---
        "block_user" to "Chặn người dùng",
        "block_user_title" to "Chặn người dùng này?",
        "block_user_msg" to "Họ sẽ không thể tìm thấy hồ sơ hoặc nhắn tin cho bạn. Bạn có thể bỏ chặn trong Cài đặt.",
        "block" to "Chặn",
        "user_unavailable" to "Người dùng không tồn tại hoặc không khả dụng.",
        "blocked_success" to "Đã chặn người dùng.",
        "error_blocking" to "Lỗi khi chặn: ",
        "error_friend_request" to "Lỗi gửi kết bạn: ",
        "error_cancel_request" to "Lỗi hủy lời mời: ",
        "error_create_chat" to "Không thể tạo cuộc trò chuyện",
        "user_inactive" to "Người dùng này không còn hoạt động",
        "blocked_msg_error" to "Bạn không thể nhắn tin cho người này.",

        // --- REVIEW & RATING ---
        "rating_reviews" to "Đánh giá & Nhận xét",
        "see_reviews" to "Xem đánh giá",
        "write_review" to "Viết đánh giá",
        "write_review_hint" to "Chia sẻ trải nghiệm của bạn...",
        "submit_review" to "Gửi đánh giá",
        "delete_review" to "Xóa đánh giá",
        "review_empty_error" to "Vui lòng chọn số sao.",
        "not_enough_messages" to "Cần nhắn tin qua lại ít nhất 10 tin để đánh giá.",
        "load_more_reviews" to "Xem thêm đánh giá",
        "no_reviews_yet" to "Chưa có đánh giá nào.",
        "your_rating" to "Đánh giá của bạn",
        "delete_review_confirm" to "Xóa đánh giá của bạn?",

        // --- REPORT DIALOG (POSTS & USERS) ---
        "report_title" to "Báo cáo bài viết",
        "report_user_title" to "Báo cáo người dùng",
        "report_reason" to "Lý do báo cáo",
        "select_reason" to "Chọn lý do",

        // Reasons for POSTS
        "report_fraud" to "Lừa đảo hoặc Spam",
        "report_inappropriate" to "Nội dung không phù hợp",
        "report_trading" to "Hàng hóa/Giao dịch bị cấm",
        "report_offensive" to "Ngôn từ xúc phạm / Thù ghét",
        "report_misinformation" to "Thông tin sai lệch",

        // Reasons for USERS (Mới)
        "report_reason_spam" to "Spam hoặc Lừa đảo",
        "report_reason_harassment" to "Quấy rối hoặc Bắt nạt",
        "report_reason_fake" to "Tài khoản giả mạo",
        "report_reason_inappropriate" to "Nội dung không phù hợp",
        "report_reason_other" to "Khác",

        "report_other" to "Khác",
        "report_other_hint" to "Vui lòng ghi rõ lý do...",
        "report_select_reason_required" to "Vui lòng chọn một lý do",
        "report_description" to "Mô tả thêm",
        "report_description_hint" to "Cung cấp thêm chi tiết về vấn đề (Tùy chọn)",
        "report_cancel" to "Hủy",
        "report_submit" to "Gửi",
        "report_submitted_success" to "Đã gửi báo cáo. Cảm ơn bạn!",
        "report_user" to "Báo cáo người dùng",
        "report_duplicate_post" to "Bạn đã báo cáo bài viết này rồi",
        "report_duplicate_user" to "Bạn đã báo cáo người dùng này rồi",
        "report_submitted_success" to "Đã gửi báo cáo. Cảm ơn bạn!",
        "user_unavailable" to "Người dùng không tồn tại hoặc đã bị khóa",
        "user_inactive" to "Tài khoản này hiện không hoạt động",
        "blocked_msg_error" to "Bạn không thể gửi tin nhắn cho người này",
        "error" to "Lỗi",

        // Notifications Screen
        "notifications" to "Thông báo",
        "mark_all_read" to "Đọc tất cả",
        "social" to "Xã hội",
        "system" to "Hệ thống",
        "clear_all" to "Xóa tất cả",
        "no_notifications" to "Chưa có thông báo nào",
        "social_empty_msg" to "Các tương tác như thích, bình luận và lời mời kết bạn sẽ xuất hiện ở đây.",
        "emergency_empty_msg" to "Các cảnh báo hệ thống và cập nhật khẩn cấp sẽ được hiển thị ở đây.",
        "friend_reject" to "Từ chối",
        "Warning" to "Cảnh báo",
        "Announcement" to "Thông báo",

        // Notification Types
        "notif_liked_post" to "đã thích bài viết của bạn",
        "notif_liked_comment" to "đã thích bình luận của bạn",
        "notif_commented" to "đã bình luận",
        "notif_replied" to "đã trả lời bình luận của bạn",
        "notif_friend_request" to "đã gửi cho bạn lời mời kết bạn",
        "notif_sos_accepted" to "đã chấp nhận yêu cầu hỗ trợ của bạn",
        "notif_emergency_approved" to "Yêu cầu khẩn cấp của bạn đã được phê duyệt",
        "notif_emergency_rejected" to "Yêu cầu khẩn cấp của bạn đã bị từ chối",

        // Time ago labels
        "time_just_now" to "Vừa xong",
        "time_minutes_ago" to "phút trước",
        "time_hours_ago" to "giờ trước",
        "time_days_ago" to "ngày trước",
        // ... Các key khác ...
        "tab_everyone" to "Tất cả",
        "tab_foryou" to "Dành cho bạn",
        "tab_saved" to "Đã lưu",
        "tab_support" to "Cứu trợ",
        "tab_service" to "Dịch vụ",
        "empty_saved_posts" to "Chưa có bài viết đã lưu",
        "empty_posts" to "Không tìm thấy bài viết",
        "cancel" to "Hủy",
        "save" to "Lưu",
        "confirm" to "Xác nhận",
        "back" to "Quay lại",
        "close" to "Đóng",
        "next" to "Tiếp theo",
        "edit" to "Chỉnh sửa",
        "copy" to "Sao chép",
        "yes" to "Có",
        "no" to "Không",
        "apply" to "Áp dụng",
        "loading" to "Đang tải...",
        "error" to "Lỗi",
        "success" to "Thành công",
        "delete" to "Xóa",
        "search" to "Tìm kiếm",
        "filter" to "Bộ lọc",
        "clear_filter" to "Xóa lọc",
        "select_city" to "Chọn Tỉnh/Thành",
        "select_district" to "Chọn Quận/Huyện",
        "select_category" to "Chọn Danh mục",
        "all_locations" to "Tất cả địa điểm",
        "all_categories" to "Tất cả danh mục",
        "what_on_your_mind" to "Bạn đang nghĩ gì?",
        "post_button" to "Đăng bài",
        "post_success" to "Đăng bài thành công!",
        "login" to "Đăng nhập",
        "register" to "Đăng ký",
        "logout" to "Đăng xuất",
        "profile_title" to "Hồ sơ",
        "chat_title" to "Tin nhắn",
        "notifications" to "Thông báo",


    )
}